version: "3.1"

services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_DB: pawpoint
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
      - 8080:8080
